// ─── Error Codes ───
// Standardized error codes for consistent API responses

export const ErrorCodes = {
  // ─── General ───
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ─── Auth ───
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  WEAK_PASSWORD: 'WEAK_PASSWORD',

  // ─── User ───
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  AVATAR_UPLOAD_FAILED: 'AVATAR_UPLOAD_FAILED',

  // ─── House ───
  HOUSE_NOT_FOUND: 'HOUSE_NOT_FOUND',
  HOUSE_UNAVAILABLE: 'HOUSE_UNAVAILABLE',
  HOUSE_CREATE_FAILED: 'HOUSE_CREATE_FAILED',
  HOUSE_UPDATE_FAILED: 'HOUSE_UPDATE_FAILED',
  HOUSE_DELETE_FAILED: 'HOUSE_DELETE_FAILED',

  // ─── Booking ───
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANNOT_CANCEL: 'BOOKING_CANNOT_CANCEL',
  BOOKING_INVALID_DATES: 'BOOKING_INVALID_DATES',
  BOOKING_STATUS_INVALID: 'BOOKING_STATUS_INVALID',

  // ─── Review ───
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  INVALID_RATING: 'INVALID_RATING',

  // ─── Messaging ───
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',

  // ─── Notification ───
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  DEVICE_TOKEN_INVALID: 'DEVICE_TOKEN_INVALID',
  PUSH_NOTIFICATION_FAILED: 'PUSH_NOTIFICATION_FAILED',

  // ─── Location ───
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  GEOCODING_FAILED: 'GEOCODING_FAILED',

  // ─── Payment ───
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  REFUND_FAILED: 'REFUND_FAILED',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',

  // ─── File Upload ───
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
};

export default ErrorCodes;
